### ISSUE TITLE
add post request

### ISSUE THREAD

**Issue by nofearOnline** [Rogozin-high-school/lab_control_panel#3]
........

**Comment by ron-popov** [comment]
@nofearOnline isn't the todo pretty obvious because this is an issue ?

**Comment by nofearOnline** [comment]
No because the issue labels can be change, so for first the label is to do
and than when someone start to solve the issue he change the label to doing
so no one else will do it

**Comment by ron-popov** [comment]
Ok, but you could drop the TODO tag and just leave the "doing" tag.

**Comment by StavAlush27** [comment]
i added a new handler that get the req on post and open a new page that shows the password
